### PR TITLE
Croatian language

### PR DESCRIPTION
**Pull request by tomsh-hr**
Hi, here is Croatian language translation

### CODE REVIEW

**Comment by kenlog** [comment]
Hi @tomsh-hr welcome. Thanks for the contribution! 
Need to add initialization of the translation to the json file https://github.com/docpht/docpht/blob/master/src/translations/code-translations.json#L1
After this i can merge :wink:

**Review by kenlog — APPROVED** [review]
:+1:

**Comment by itstomsh** [comment]
Hi

> Hi @tomsh-hr welcome. Thanks for the contribution!
> Need to add initialization of the translation to the json file https://github.com/docpht/docpht/blob/master/src/translations/code-translations.json#L1
> After this i can merge wink

You're welcome :D. Added two more translation messages to Croatian language that was missing in Italian right before Backup management, Backup and Backups

**Comment by kenlog** [comment]
@tomsh-hr They are included :+1: https://github.com/docpht/docpht/blob/master/src/translations/hr_HR.php#L174

**Comment by itstomsh** [comment]
@kenlog yes, i added them. Translations still missing in other languages
https://github.com/docpht/docpht/blob/e7f849bdb1a9350743be7e3be1c5e1b313b2e866/src/translations/it_IT.php#L174

**Comment by kenlog** [comment]
ok, thanks for reporting.

**Comment by creecros** [comment]
@kenlog check nachostudio.ml when u get a chance

**Pull request merged**
