### PR TITLE
Fix zip filename and timestamp after global restore

### PR DESCRIPTION
**Pull request by Bubka**
Hi,

Here are some changes for windows users to fix bad zip filename (the colons is a restricted characters) and to fix access to internal zip files (when using the `zip://` protocol) during backup processing.

I also add a change to improve the situation after a backup restore. It avoid page versions to be all timestamped with the same date & time value (the one of the backup creation time)

### CODE REVIEW

**Comment by Bubka** [comment]
I didn't wanted to go deeper with the timestamps in zip filenames before you reviewed it but I think it should be extended to the backup zip files (and replace the `uniqid()` ?)

**Comment by kenlog** [comment]
Hi @Bubka thanks also for this other contribution! Before joining you must try to work correctly. In this case I ask @creecros who is a Windows user to try it for me, thank you very much. As far as uniqid () is concerned, it serves to prevent the name of the file stored on the server from being predictable and to prevent any download by a user or script simply by providing the name of the archived files.

**Comment by Bubka** [comment]
I was wondering why uniqid() is used, i suspected something like that. Thanks for the explanation, it makes sense.

> Before joining you must try to work correctly.

I'm not sure to understand what you means exactly. Do you want me to submit changes in a different manner ?

**Comment by kenlog** [comment]
@Bubka before performing the merge it is necessary to perform functional tests. Since I only use Linux I am unable to test these changes and for this reason I asked @creecros

**Comment by Bubka** [comment]
@kenlog Of course, i fully agree with that :ok_hand:

**Comment by creecros** [comment]
Gimme a day or two to take a look.

**Comment by kenlog** [comment]
Hey :wave: @creecros no difficulty :+1: . Service alert there are problems with nachostudio ssl :unlock:

**Review by creecros — APPROVED** [review]

**Comment by creecros** [comment]
changes tested fine
@kenlog nachostudio should be back up

**Comment by kenlog** [comment]
Hi @creecros thank you very much. Then I proceed with the merge. Nachostudio now works :+1:

**Pull request merged**
